image: python:3.10

stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python -V
  - pip install -r requirements.txt
  - pip install flake8 pylint mypy isort black

lint:
  stage: lint
  script:
    # Check for syntax errors and undefined names
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # Check for code style issues (not fail-fast)
    - flake8 . --count --max-complexity=10 --max-line-length=100 --statistics
    # Check code formatting
    - black --check .
    # Check import sorting
    - isort --check-only --profile black .
    # Check for unused imports, undefined variables, unused variables
    - pylint --disable=all --enable=unused-import,undefined-variable,unused-variable app
    # Check type annotations
    - mypy app

test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest tests/ --cov=app
  only:
    - main
    - merge_requests

build:
  stage: build
  script:
    - echo "Running build stage"
  only:
    - main
    - tags
