"""Add Razorpay payment tables

Revision ID: 2c6e24f9940e
Revises: 9c275f4ff14b
Create Date: 2025-05-30 10:19:01.416669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e24f9940e'
down_revision = '9c275f4ff14b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
